SELECT NAME, LISTPRICE
FROM Production.PRODUCT
WHERE LISTPRICE < (
	SELECT AVG(LISTPRICE)
	FROM Production.Product)

SELECT NAME, LISTPRICE,
	(SELECT AVG(LISTPRICE) FROM PRODUCTION.Product) PROMEDIO, (LISTPRICE - (SELECT AVG(LISTPRICE) FROM PRODUCTION.PRODUCT)) AS DIFERENCIA
FROM Production.PRODUCT

SELECT PRODUCTID, NAME FROM Production.Product
WHERE LISTPRICE = (SELECT MAX(LISTPRICE) FROM Production.Product)

SELECT P1.ProductSubcategoryID, P1.ListPrice, P1.PRODUCTID, P1.Name
	FROM Production.Product P1
	WHERE LISTPRICE = (
		SELECT MIN(LISTPRICE)
		FROM PRODUCTION.PRODUCT P2
		WHERE P1.ProductSubcategoryID = P2.ProductSubcategoryID)
	ORDER BY P1.ProductSubcategoryID

