SELECT DISTINCT PRODUCTID
 FROM SALES.SalesOrderDetail

SELECT PRODUCTID
 FROM SALES.SalesOrderDetail
 UNION ALL
SELECT PRODUCTID
 FROM PRODUCTION.WORKORDER

SELECT PRODUCTID
 FROM SALES.SalesOrderDetail
 UNION
SELECT PRODUCTID
 FROM PRODUCTION.WORKORDER

SELECT BUSINESSENTITYID,
 CASE WHEN GENDER = 'M' THEN 'MASCULINO'
 ELSE 'FEMENINO'
 END SEXO
 FROM HUMANRESOURCES.EMPLOYEE

SELECT	BusinessEntityID, SalariedFlag
 FROM HumanResources.Employee
 ORDER BY 
 CASE WHEN SALARIEDFLAG = 1 THEN BusinessEntityID END DESC,
 CASE WHEN SalariedFlag = 0 THEN BusinessEntityID END;