--CONVERSIONES IMPLICITAS
--UN INT A UN VARCHAR
DECLARE @NUM1 INT = 1521
DECLARE @texto VARCHAR(50) = @NUM1
SELECT @NUM1, @texto

--UN BIT A UN SMALLINT
DECLARE @FLAG BIT = 1
DECLARE @NUM SMALLINT = @FLAG
SELECT @FLAG, @NUM

--UN INT A UN DECIMAL
DECLARE @NUM2 INT = 12352
DECLARE @NUM3 DECIMAL(9,2) = @NUM2
SELECT @NUM2, @NUM3

----------------------------------------------------------------

--CONVERSIONES EXPLICITAS
--A) FECHA
SELECT 
GETDATE(),
CONVERT(VARCHAR, GETDATE(), 101),
CONVERT(VARCHAR, GETDATE(), 103), 
CONVERT(VARCHAR, GETDATE(), 105), 
CONVERT(VARCHAR, GETDATE(),111), 
CONVERT(VARCHAR, GETDATE(), 112),
CAST(GETDATE() AS TIME(0))

--B) NUMERICOS
DECLARE @NUM4 DECIMAL(10,2) = 31020.56
SELECT
ORIGINAL = @NUM4,
ENTERO = CAST(@NUM4 AS INT),
[SMALLINT] = CAST(@NUM4 AS SMALLINT),
[FLOAT] = CAST(@NUM4 AS FLOAT),
[TEXTO] = CAST(@NUM4 AS VARCHAR(10))