USE DB_Educacion_IT
GO
--1) ******************INSERT*******************************

--A) CREO TABLA TMP_CUENTAS, LUEGO INSERT REGISTRO EN LA MISMA
--B) CREO TABLA CUENTAS E INSERTO TODOS LOS REGISTROS DE TMP_CUENTAS EN LA TABLA CUENTAS
IF NOT EXISTS
(
	SELECT TOP 1 1 FROM SYS.TABLES WHERE NAME = 'TMP_CUENTAS'
)
BEGIN
	CREATE TABLE dbo.TMP_CUENTAS
	(
		NUMERO_CUENTA VARCHAR(5) NOT NULL,
		GRUPO_CUENTA VARCHAR(4) NOT NULL,
		NOMBRE_CUENTA VARCHAR(100) NOT NULL,
		PREFJIO CHAR(4) NOT NULL,
		ACTIVO BIT NOT NULL,
		CONSTRAINT [PK_TMP_CUENTAS] PRIMARY KEY CLUSTERED 
		(
		NUMERO_CUENTA ASC
		)
	)
END
TRUNCATE TABLE dbo.TMP_CUENTAS
INSERT INTO dbo.TMP_CUENTAS
(
NUMERO_CUENTA,
GRUPO_CUENTA,
NOMBRE_CUENTA,
PREFJIO,
ACTIVO
)
VALUES 
('1324','0111','MAPFRE','VW',CAST(0 AS BIT)),
('1349','0024','HDI COMERCIOS','LUP',CAST(1 AS BIT)),
('1350','0024','HDI CONSORCIOS','LUP',CAST(1 AS BIT)),
('1351','0024','HDI CRI','LUP',CAST(1 AS BIT)),
('1510','0047','DKS Asesores de Seguros','DKS',CAST(0 AS BIT)),
('1546','0049','PSA','PG',CAST(0 AS BIT)),
('1560','0111','MAPFRE','AL',CAST(0 AS BIT)),
('1564','0053','BANCO SUPERVIELLE ASISTENCIA HOGAR','SP',CAST(0 AS BIT)),
('1579','0043','BANCO ICBC ASISTENCIA HOGAR','IC',CAST(0 AS BIT)),
('1601','0063','BANCO HIPOTECARIO COMERCIOS','BH',CAST(0 AS BIT)),
('1629','0067','ASISTENCIA VIAL BAIONI','AVB',CAST(0 AS BIT)),
('1636','0024',' HDI TRASLADO DE PERSONA FALLECIDA','LUP',CAST(0 AS BIT)),
('1637','0070','GENERAL MOTORS','GM',CAST(0 AS BIT)),
('1645','0072','TOYOTA','TO',CAST(0 AS BIT)),
('1665','0074','ASISTENCIA VIAL WILLIS','WI',CAST(0 AS BIT)),
('1677','0077','LA CAJA FIAT','FI',CAST(0 AS BIT)),
('1679','0074','PROSEGUR ASISTENCIA HOGAR','WI',CAST(0 AS BIT)),
('1717','0077','ASISTENCIA VIAL PARA PARTICULARES, TAXIS Y REMISES','FI',CAST(0 AS BIT)),
('1719','0077','FIAT LA NUEVA Autos y Pickups','FI',CAST(0 AS BIT)),
('1720','0077','FIAT LA NUEVA Taxis CABA','FI',CAST(0 AS BIT)),
('1721','0077','FIAT LA NUEVA Taxis interior','FI',CAST(0 AS BIT)),
('1722','0011','MAPFRE','FO',CAST(0 AS BIT)),
('1728','0111','OLAS-AUTOS','OL',CAST(0 AS BIT)),
('1755','0111','HDI MASCOTAS','LUP',CAST(0 AS BIT)),
('1757','0006','NACION SEGUROS ASISTENCIA HOGAR','NS',CAST(0 AS BIT)),
('1761','0006','NACION SEGUROS ASISTENCIA COMERCIO','NS',CAST(0 AS BIT)),
('1762','0006','NACION SEGUROS ASISTENCIA CONSORCIO','NS',CAST(0 AS BIT)),
('1763','0006','NACION SEGUROS SERVICIOS PARA EL SEGURO DE SALUD','NS',CAST(0 AS BIT)),
('1764','0006','NACION SEGUROS AP JUBILADOS','NS',CAST(0 AS BIT)),
('1789','0024','HDI HOGAR TECNOLOGICO LAD','LUP',CAST(1 AS BIT)),
('1790','0024','HDI VIAL  TECNOLOGICO LAD','LUP',CAST(1 AS BIT)),
('1797','0043','BANCO ICBC PAYROLL CAPITADO','IC',CAST(0 AS BIT)),
('1803','0093','LAD  SEGURO BICI','GYS',CAST(0 AS BIT)),
('1815','0085','OLAS-MOTOS','OL',CAST(0 AS BIT)),
('1852','0024','HDI - SINIESTROS','LUP',CAST(1 AS BIT)),
('1892','0004','GALICIA SEGUROS','BG',CAST(0 AS BIT)),
('1905','0111','ASISTENCIA ATM SUPERVIELLE SEGUROS','SP',CAST(0 AS BIT)),
('1958','0024','HDI - MOTO 150 FULL','LUP',CAST(1 AS BIT))


IF NOT EXISTS
(
	SELECT TOP 1 1 FROM SYS.TABLES WHERE NAME = 'CUENTAS'
)
BEGIN
	CREATE TABLE dbo.CUENTAS
	(
		NUMERO_CUENTA VARCHAR(5) NOT NULL,
		GRUPO_CUENTA VARCHAR(4) NOT NULL,
		NOMBRE_CUENTA VARCHAR(100) NOT NULL,
		PREFJIO CHAR(4) NOT NULL,
		ACTIVO BIT NOT NULL,
		CONSTRAINT [PK_CUENTAS] PRIMARY KEY CLUSTERED 
		(
		NUMERO_CUENTA ASC
		)
	)
END
TRUNCATE TABLE dbo.CUENTAS
--REALIZO LA INSERSION DE LOS DATOS DE LA TABLA TMP_CUENTAS A LA TABLA CUENTAS
INSERT INTO dbo.CUENTAS
(
NUMERO_CUENTA,
GRUPO_CUENTA,
NOMBRE_CUENTA,
PREFJIO,
ACTIVO
)
SELECT
NUMERO_CUENTA,
GRUPO_CUENTA,
NOMBRE_CUENTA,
PREFJIO,
ACTIVO
FROM TMP_CUENTAS

SELECT 'DATOS INSERTADO EN TABLA CUENTAS'
SELECT * FROM CUENTAS

--2) ******************UPDATE*******************************
--MODIFICAR LOS REGISTROS DE LA TABLA TMP_CUENTAS Y LUEGO ACTUALIZARLOS EN LA TABLA CUENTAS

UPDATE TMP_CUENTAS
SET NOMBRE_CUENTA = NOMBRE_CUENTA + ' PRUEBA'
WHERE ACTIVO = CAST(1 AS BIT)


UPDATE PP
SET 
GRUPO_CUENTA = CC.GRUPO_CUENTA,
NOMBRE_CUENTA = CC.NOMBRE_CUENTA,
PREFJIO = CC.PREFJIO,
ACTIVO = CC.ACTIVO
FROM dbo.CUENTAS PP
INNER JOIN dbo.TMP_CUENTAS CC ON CC.NUMERO_CUENTA = PP.NUMERO_CUENTA
WHERE PP.GRUPO_CUENTA <> CC.GRUPO_CUENTA
OR PP.NOMBRE_CUENTA <> CC.NOMBRE_CUENTA
OR PP.PREFJIO <> CC.PREFJIO
OR PP.ACTIVO <> CC.ACTIVO

SELECT * FROM dbo.TMP_CUENTAS
SELECT * FROM dbo.CUENTAS


--2) ******************DELETE*******************************
--A) ELIMINAR ALGUNOS REGISTROS DE LA TABLA TMP_CUENTAS 
--B) ELIMINAR DE LA TABLA CUENTAS AQUELLOS REGISTROS QUE NO EXISTEN EN LA TABLA TMP_CUENTAS
--(El objetivo del punto B), es que la tabla CUENTAS siempre tenga los mismos registros que la tabla TMP_CUENTAS

DELETE FROM dbo.TMP_CUENTAS WHERE NUMERO_CUENTA IN(1324, 1349, 1350, 1351, 1510)

DELETE PP
--SELECT PP.NUMERO_CUENTA, CC.NUMERO_CUENTA
FROM dbo.CUENTAS PP
LEFT JOIN  dbo.TMP_CUENTAS CC ON CC.NUMERO_CUENTA = PP.NUMERO_CUENTA
WHERE CC.NUMERO_CUENTA IS  NULL


--DIFERENCIA TRUNCATE VS DELETE

IF NOT EXISTS
(
	SELECT TOP 1 1 FROM SYS.TABLES WHERE NAME = 'TMP_PAISES'
)
BEGIN
	CREATE TABLE dbo.TMP_PAISES
	(
		id_pais INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(50) NOT NULL	
	)
END
TRUNCATE TABLE dbo.TMP_PAISES

INSERT INTO dbo.TMP_PAISES
(
NOMBRE
)
VALUES ('ARGENTINA'), ('BRASIL'), ('CHILE'), ('COLOMBIA')

SELECT * FROM dbo.TMP_PAISES

--*************ELIMINO LOS REGISTROS CON DELETE***************
DELETE FROM dbo.TMP_PAISES

--VUELVO A INSERTAR LOS MISMOS REGISTROS
INSERT INTO dbo.TMP_PAISES
(
NOMBRE
)
VALUES ('ARGENTINA'), ('BRASIL'), ('CHILE'), ('COLOMBIA')
--OBSERVAR QUE EL id_pais se incremnta considerando los registros que se borraron
SELECT * FROM dbo.TMP_PAISES


--*************TRUNCO LOS REGISTROS DE LA TABLA***************
TRUNCATE TABLE dbo.TMP_PAISES

--VUELVO A INSERTAR LOS MISMOS REGISTROS
INSERT INTO dbo.TMP_PAISES
(
NOMBRE
)
VALUES ('ARGENTINA'), ('BRASIL'), ('CHILE'), ('COLOMBIA')
--OBSERVAR QUE EL id_pais se reinicia
SELECT * FROM dbo.TMP_PAISES
